export interface SeatingAssignment {
  table: string;
}

export interface SeatingChart {
  [key: string]: SeatingAssignment;
}

const seatingChart: SeatingChart = {
  'Alhaji Bola Alabi': { table: 'VIP Table' },
  'Habeeb Akande': { table: 'VIP Table' },
  'Mrs Hikmat Akande': { table: 'VIP Table' },
  'Olayinka Akinmoku': { table: 'VIP Table' },
  'Dr. Samson Dopemu': { table: 'VIP Table' },
  'Dr Wale Ojo': { table: 'VIP Table' },
  'Funke Ojo': { table: 'VIP Table' },
  'Victor Adeyemo': { table: 'VIP Table' },
  'Uche Gregory': { table: 'VIP Table' },
  'Uche Evangeline': { table: 'VIP Table' },
  'Uche Hilary': { table: 'VIP Table' },
  'Uche Edith': { table: 'VIP Table' },
  'Mrs Funke Smith': { table: 'VIP Table' },
  'Otunba Femi Kalejaiye (Femkarl)': { table: 'VIP Table' },
  'Adenike Kalejaiye (Mother of the bride)': { table: 'VIP Table' },
  'Engr. Kalejaiye (Baba Bidemi)': { table: 'VIP Table' },
  'James Kalejaiye (Jamkarl)': { table: 'VIP Table' },
  'Mr Seyi Badekale (Badek)': { table: 'VIP Table' },
  'Deacon Akin Toki': { table: 'VIP Table' },
  'Uche Emmanuel': { table: 'Table 1 - Groom\'s Family' },
  'Uche Favour': { table: 'Table 1 - Groom\'s Family' },
  'Uche Promise': { table: 'Table 1 - Groom\'s Family' },
  'Dr. Hemeson': { table: 'Table 1 - Groom\'s Family' },
  'Mrs. Tessy Hemeson': { table: 'Table 1 - Groom\'s Family' },
  'Mr. Patrick Okafor': { table: 'Table 1 - Groom\'s Family' },
  'Mr. Chidueze Mba': { table: 'Table 1 - Groom\'s Family' },
  'Mrs. Vivian Mba': { table: 'Table 1 - Groom\'s Family' },
  'Mr. Nnamdi Igwilo': { table: 'Table 1 - Groom\'s Family' },
  'Mrs. Precious Igwilo': { table: 'Table 1 - Groom\'s Family' },
  'Yetunde Popoola': { table: 'Table 2 - Bridesmaids' },
  'Susan Ovoke': { table: 'Table 2 - Bridesmaids' },
  'Seyi Awofade': { table: 'Table 2 - Bridesmaids' },
  'Cynthia Okoye': { table: 'Table 2 - Bridesmaids' },
  'Biodun Oladoja': { table: 'Table 2 - Bridesmaids' },
  'Epueosi Olumekor': { table: 'Table 2 - Bridesmaids' },
  'TemiTope Ajayi': { table: 'Table 2 - Bridesmaids' },
  'Meyiwa Sobogun': { table: 'Table 2 - Bridesmaids' },
  'Thelma Okeke': { table: 'Table 2 - Bridesmaids' },
  'Purity Oshodi': { table: 'Table 2 - Bridesmaids' },
  'Itunu Kalejaiye': { table: 'Table 3 - Bride\'s Siblings' },
  'Fumbi Kalejaiye': { table: 'Table 3 - Bride\'s Siblings' },
  'David Kalejaiye': { table: 'Table 3 - Bride\'s Siblings' },
  'Modupe Abiodun': { table: 'Table 3 - Bride\'s Siblings' },
  'Antonia Okorie': { table: 'Table 3 - Bride\'s Siblings' },
  'Timileyin Kalejaiye': { table: 'Table 3 - Bride\'s Siblings' },
  'Mayowa Olugbade': { table: 'Table 3 - Bride\'s Siblings' },
  'Kunle Omomoh': { table: 'Table 3 - Bride\'s Siblings' },
  'Timi Olawuyi': { table: 'Table 3 - Bride\'s Siblings' },
  'Daniel Toki': { table: 'Table 3 - Bride\'s Siblings' },
  'Grandma Kalejaiye (Iya Benin)': { table: 'Table 4 - Kalejaiye Family' },
  'Mrs Kemi Oshodi (Mummy Purity)': { table: 'Table 4 - Kalejaiye Family' },
  'Samuel Kalejaiye (Samkal)': { table: 'Table 4 - Kalejaiye Family' },
  'Mary Kalejaiye (Iya Gold, has two kids)': { table: 'Table 4 - Kalejaiye Family' },
  'Motunrayo Kalejaiye (Mummy Debby)': { table: 'Table 4 - Kalejaiye Family' },
  'Mrs Toun Omomoh (Iya Iyere)': { table: 'Table 4 - Kalejaiye Family' },
  'Mrs Bunmi (Iya Obeyi)': { table: 'Table 4 - Kalejaiye Family' },
  'Mrs Kalejaiye (Iya Anu)': { table: 'Table 4 - Kalejaiye Family' },
  'Mrs Yinka Kalejaiye': { table: 'Table 4 - Kalejaiye Family' },
  'Mrs Funmi Kalejaiye': { table: 'Table 4 - Kalejaiye Family' },
  'Mrs. Onyebuchi Ogu': { table: 'Table 5 - Groom\'s Family' },
  'Mrs. Ifeanyi Ogu': { table: 'Table 5 - Groom\'s Family' },
  'Mrs. Ikechukwu Ogu': { table: 'Table 5 - Groom\'s Family' },
  'Mr. Godwin Dike': { table: 'Table 5 - Groom\'s Family' },
  'Mrs. Roseline Dike': { table: 'Table 5 - Groom\'s Family' },
  'Madam Lolo': { table: 'Table 5 - Groom\'s Family' },
  'Mrs. Tina Okafor': { table: 'Table 5 - Groom\'s Family' },
  'Eze Elect. Martins Akuwudike': { table: 'Table 5 - Groom\'s Family' },
  'Mrs. Nkeiruka Akuwudike': { table: 'Table 5 - Groom\'s Family' },
  'Fortune Uche': { table: 'Table 6 - Groomsmen' },
  'Temitayo Olatunji': { table: 'Table 6 - Groomsmen' },
  'Temi Azeezz': { table: 'Table 6 - Groomsmen' },
  'Tobi Popoola': { table: 'Table 6 - Groomsmen' },
  'Tomiwa Kolawole': { table: 'Table 6 - Groomsmen' },
  'Pio Okeke': { table: 'Table 6 - Groomsmen' },
  'Danjuma': { table: 'Table 6 - Groomsmen' },
  'Tolulope Oyejinmi': { table: 'Table 6 - Groomsmen' },
  'Odunayo Akintola': { table: 'Table 6 - Groomsmen' },
  'Timi Aderemi': { table: 'Table 6 - Groomsmen' },
  'Shola Kalejaiye (Shola Femkal)': { table: 'Table 7 - Kalejaiye Family' },
  'Chimamanda Adefolawe Ogueri': { table: 'Table 7 - Kalejaiye Family' },
  'Mr Seyi Kalejaiye': { table: 'Table 7 - Kalejaiye Family' },
  'Titi Tanimowo (Iya Dona, has TWO children)': { table: 'Table 7 - Kalejaiye Family' },
  'Bola Kalejaiye (Tinted)': { table: 'Table 7 - Kalejaiye Family' },
  'Mrs Bose Orefuye (Bose Abuja)': { table: 'Table 7 - Kalejaiye Family' },
  'Mr Biyi Orefuye (Biyi Oworo)': { table: 'Table 7 - Kalejaiye Family' },
  'Mrs Orefuye (Iya blessing)': { table: 'Table 7 - Kalejaiye Family' },
  'Mrs Agnes Kalejaiye (Iya Bidemi)': { table: 'Table 7 - Kalejaiye Family' },
  'Mrs Blessing Omomoh (Blessing Iyere)': { table: 'Table 8 - Kalejaiye Family' },
  'Esther Ouetunji (Blessing\'s friend)': { table: 'Table 8 - Kalejaiye Family' },
  'Mary Joseph (Blessing\'s friend)': { table: 'Table 8 - Kalejaiye Family' },
  'Daniel Kalejaiye': { table: 'Table 8 - Kalejaiye Family' },
  'Yetunde Orefuye (Iya Agba)': { table: 'Table 8 - Kalejaiye Family' },
  'Sesan': { table: 'Table 8 - Kalejaiye Family' },
  'Iyawo Sesan': { table: 'Table 8 - Kalejaiye Family' },
  'Mr Efuneye (Baba Ololo)': { table: 'Table 8 - Kalejaiye Family' },
  'Mrs Augustina (Tina)': { table: 'Table 8 - Kalejaiye Family' },
  'Mrs Boye': { table: 'Table 8 - Kalejaiye Family' },
  'Bunmi Famogbiele': { table: 'Table 9 - Mrs Funke Smith\'s Guests' },
  'Eziaku Obidegwu': { table: 'Table 9 - Mrs Funke Smith\'s Guests' },
  'Ronke Benson': { table: 'Table 9 - Mrs Funke Smith\'s Guests' },
  'Laide Afolabi Ogunmefun': { table: 'Table 9 - Mrs Funke Smith\'s Guests' },
  'Gladys Yusuff': { table: 'Table 9 - Mrs Funke Smith\'s Guests' },
  'Musleemot Akinola': { table: 'Table 9 - Mrs Funke Smith\'s Guests' },
  'Mr. Akinola': { table: 'Table 9 - Mrs Funke Smith\'s Guests' },
  'Mrs. Tutu Bakare': { table: 'Table 9 - Mrs Funke Smith\'s Guests' },
  'Mrs Sekinot Fetuga': { table: 'Table 9 - Mrs Funke Smith\'s Guests' },
  'Banjo Olaniyan': { table: 'Table 9 - Mrs Funke Smith\'s Guests' },
  'Mayowa Arowolo': { table: 'Table 10 - Ibadan Golf Club' },
  'Alhassan Issa': { table: 'Table 10 - Ibadan Golf Club' },
  'Monday Edeth': { table: 'Table 10 - Ibadan Golf Club' },
  'Dr. Kehinde Adebayo': { table: 'Table 10 - Ibadan Golf Club' },
  'John Cross Moses Madu': { table: 'Table 10 - Ibadan Golf Club' },
  'Dayo Adelaku': { table: 'Table 10 - Ibadan Golf Club' },
  'Folarin Laosun': { table: 'Table 10 - Ibadan Golf Club' },
  'Layefa Ebitonmo': { table: 'Table 10 - Ibadan Golf Club' },
  'Doubra Ebitonmo': { table: 'Table 10 - Ibadan Golf Club' },
  'Ifeoluwa Benedict': { table: 'Table 10 - Ibadan Golf Club' },
  'Mrs Bisi Odetoki (Iya Tope)': { table: 'Table 11 - Odetoki Family' },
  'Mrs Bosede Odetoki (Iya Kayode)': { table: 'Table 11 - Odetoki Family' },
  'Mrs Bisi Olawuyi (Iya Dolapo)': { table: 'Table 11 - Odetoki Family' },
  'Mrs Shade Olugbade (Iya Bolu)': { table: 'Table 11 - Odetoki Family' },
  'Mrs Kehinde Oluwatumibi (Iya Favour)': { table: 'Table 11 - Odetoki Family' },
  'Mrs Taye (Iya kindness)': { table: 'Table 11 - Odetoki Family' },
  'Mrs Gbemisola Odetoki (Iya Bola)': { table: 'Table 11 - Odetoki Family' },
  'Bola Ojelabi (has ONE child)': { table: 'Table 11 - Odetoki Family' },
  'Mrs Adejumo (Iya Dominion, has TWO children)': { table: 'Table 11 - Odetoki Family' },
  'Mr Adegoke Kalejaiye (Daddy Dominion)': { table: 'Table 11 - Odetoki Family' },
  'Mr Badekale (PPA)': { table: 'Table 12 - PPA' },
  'Mr Sharry (PPA)': { table: 'Table 12 - PPA' },
  'Mr Akeem Sultan (PPA)': { table: 'Table 12 - PPA' },
  'Mr Abayomi Kalejaiye (PPA)': { table: 'Table 12 - PPA' },
  'Mr Sheriff (PPA)': { table: 'Table 12 - PPA' },
  'Mr Ademola (PPA)': { table: 'Table 12 - PPA' },
  'Mr Wasiu (PPA)': { table: 'Table 12 - PPA' },
  'Mr Bankole (PPA)': { table: 'Table 12 - PPA' },
  'Mr Alowonle (PPA)': { table: 'Table 12 - PPA' },
  'Mr Akinola (PPA)': { table: 'Table 12 - PPA' },
  'Dr. Bimbo Adejonwo': { table: 'Table 13 - Mrs Funke Smith\'s Guests' },
  'Mrs. Angela Obiekwugo': { table: 'Table 13 - Mrs Funke Smith\'s Guests' },
  'Otunba Toyin Osibogun': { table: 'Table 13 - Mrs Funke Smith\'s Guests' },
  'Chinyere Okoromadu': { table: 'Table 13 - Mrs Funke Smith\'s Guests' },
  'Gbenga Bamiro': { table: 'Table 13 - Mrs Funke Smith\'s Guests' },
  'Motola Bashorun': { table: 'Table 13 - Mrs Funke Smith\'s Guests' },
  'Peju Adenuga': { table: 'Table 13 - Mrs Funke Smith\'s Guests' },
  'Gbolahun Adenuga': { table: 'Table 13 - Mrs Funke Smith\'s Guests' },
  'Precious Otaigbe': { table: 'Table 13 - Mrs Funke Smith\'s Guests' },
  'Ife Akpantaku': { table: 'Table 14 - Couple\'s Friends' },
  'Zainab Adetola': { table: 'Table 14 - Couple\'s Friends' },
  'Shade Amosu': { table: 'Table 14 - Couple\'s Friends' },
  'Ifeoluwa Olurin': { table: 'Table 14 - Couple\'s Friends' },
  'Omah Evans': { table: 'Table 14 - Couple\'s Friends' },
  'Fayokemi Bamidele': { table: 'Table 14 - Couple\'s Friends' },
  'Jennifer Benedict': { table: 'Table 14 - Couple\'s Friends' },
  'Chidinma': { table: 'Table 14 - Couple\'s Friends' },
  'Oyindamola Adepeju': { table: 'Table 14 - Couple\'s Friends' },
  'Ifeayin Okoro': { table: 'Table 14 - Couple\'s Friends' },
  'Mrs Kemi Toki': { table: 'Table 15 - Odetoki Family' },
  'Mrs Modupe Kazeem': { table: 'Table 15 - Odetoki Family' },
  'Mrs Akintoki': { table: 'Table 15 - Odetoki Family' },
  'Mrs Olaitan Idanwekhai (has TWO children)': { table: 'Table 15 - Odetoki Family' },
  'Mr Jide (Daddy Kayode)': { table: 'Table 15 - Odetoki Family' },
  'Mr Sunday Odetoki (Daddy Tope)': { table: 'Table 15 - Odetoki Family' },
  'Mr Bimbo Toki': { table: 'Table 15 - Odetoki Family' },
  'Abbey Kazeem': { table: 'Table 15 - Odetoki Family' },
  'Mrs Yemisi Omotunde (Iya Ibeji, has ONE child)': { table: 'Table 15 - Odetoki Family' },
  'Mr Shola Omotunde (Baba Ibeji)': { table: 'Table 15 - Odetoki Family' },
  'Mr Dare (PPA)': { table: 'Table 16 - PPA' },
  'Mr Tunde (PPA)': { table: 'Table 16 - PPA' },
  'Mr Segun (PPA)': { table: 'Table 16 - PPA' },
  'Mr Shamel (PPA)': { table: 'Table 16 - PPA' },
  'Mr Deji Mabe (PPA)': { table: 'Table 16 - PPA' },
  'Mr Deji (Pick 2) (PPA)': { table: 'Table 16 - PPA' },
  'Mr Qudus (PPA)': { table: 'Table 16 - PPA' },
  'Mr Iyere (PPA)': { table: 'Table 16 - PPA' },
  'Mr Wale (PPA)': { table: 'Table 16 - PPA' },
  'Mr Polar (PPA)': { table: 'Table 16 - PPA' },
  'Mr. Towoju': { table: 'Table 17 - First Bank Staff' },
  'Mrs. Towoju': { table: 'Table 17 - First Bank Staff' },
  'Barr. Towoju': { table: 'Table 17 - First Bank Staff' },
  'Mr. Nnaji': { table: 'Table 17 - First Bank Staff' },
  'Mrs. Rossana Nnaji': { table: 'Table 17 - First Bank Staff' },
  'Madam Uche Mbey': { table: 'Table 17 - First Bank Staff' },
  'Madam Gina': { table: 'Table 17 - First Bank Staff' },
  'Shade Salam': { table: 'Table 17 - First Bank Staff' },
  'Mr. Kingsley Ezeribe': { table: 'Table 17 - First Bank Staff' },
  'Mrs. Sarah Samuel': { table: 'Table 17 - First Bank Staff' },
  'Cynthia Uduchukwu': { table: 'Table 18 - Couple\'s Friends' },
  'Emmanuella Adesanya': { table: 'Table 18 - Couple\'s Friends' },
  'Annette Okoh': { table: 'Table 18 - Couple\'s Friends' },
  'Sayo Ogunfowora': { table: 'Table 18 - Couple\'s Friends' },
  'Darlington Kelvin': { table: 'Table 18 - Couple\'s Friends' },
  'Bisola Ogunjumelo': { table: 'Table 18 - Couple\'s Friends' },
  'Bolu Adesanya': { table: 'Table 18 - Couple\'s Friends' },
  'Temi Ajayi': { table: 'Table 18 - Couple\'s Friends' },
  'Mark Steve': { table: 'Table 18 - Couple\'s Friends' },
  'Stephnie Okoye': { table: 'Table 18 - Couple\'s Friends' },
  'Mrs Ganiyat': { table: 'Table 19 - Bride\'s Mum\'s Friends' },
  'Mrs Funmi': { table: 'Table 19 - Bride\'s Mum\'s Friends' },
  'Mrs Kudi': { table: 'Table 19 - Bride\'s Mum\'s Friends' },
  'Mrs Ashabi (Iya Nifemi)': { table: 'Table 19 - Bride\'s Mum\'s Friends' },
  'Mrs Omolara (Iya Dolapo)': { table: 'Table 19 - Bride\'s Mum\'s Friends' },
  'Mrs Adedoja (Iya Aliyah)': { table: 'Table 19 - Bride\'s Mum\'s Friends' },
  'Mrs Adetutu Kalejaiye': { table: 'Table 19 - Bride\'s Mum\'s Friends' },
  'Mrs Rufiat (Iya Sheriff)': { table: 'Table 19 - Bride\'s Mum\'s Friends' },
  'Mrs Ruka (Iya Basit)': { table: 'Table 19 - Bride\'s Mum\'s Friends' },
  'Mrs Toyin (Iya Oja)': { table: 'Table 19 - Bride\'s Mum\'s Friends' },
  'Mr Ogar (PPA)': { table: 'Table 20 - PPA' },
  'Mr Osondu (PPA)': { table: 'Table 20 - PPA' },
  'Mr Ajepe (PPA)': { table: 'Table 20 - PPA' },
  'Mr Seun (PPA)': { table: 'Table 20 - PPA' },
  'Mr Laide (PPA)': { table: 'Table 20 - PPA' },
  'Mr Doyin (PPA)': { table: 'Table 20 - PPA' },
  'Mrs Eyinfunjowo (PPA)': { table: 'Table 20 - PPA' },
  'Alhaji Oloko (PPA)': { table: 'Table 20 - PPA' },
  'Mabe (PPA)': { table: 'Table 20 - PPA' },
  'Master Ani': { table: 'Table 21 - First Bank Staff' },
  'Mrs. Ogechi Ani': { table: 'Table 21 - First Bank Staff' },
  'Mrs. Margaret Onwurdi': { table: 'Table 21 - First Bank Staff' },
  'Mr. Onyeka Chiwuzor': { table: 'Table 21 - First Bank Staff' },
  'Mr. Shittu Abidemi': { table: 'Table 21 - First Bank Staff' },
  'Mr. Johnson Titiloye': { table: 'Table 21 - First Bank Staff' },
  'Miss Ufuoma Emmanuel': { table: 'Table 21 - First Bank Staff' },
  'Jane Imamu': { table: 'Table 21 - First Bank Staff' },
  'Josephine Abokede': { table: 'Table 21 - First Bank Staff' },
  'Mrs. Amarachi Kolade': { table: 'Table 21 - First Bank Staff' },
  'Taofeekat Kelani': { table: 'Table 22 - Couple\'s Friends' },
  'Faruq Kelani': { table: 'Table 22 - Couple\'s Friends' },
  'Opaaje Aminat': { table: 'Table 22 - Couple\'s Friends' },
  'Oyindamola Phillip Timothy': { table: 'Table 22 - Couple\'s Friends' },
  'Dorcas Fayemi': { table: 'Table 22 - Couple\'s Friends' },
  'Benita Okeh': { table: 'Table 22 - Couple\'s Friends' },
  'George Asuai': { table: 'Table 22 - Couple\'s Friends' },
  'Dennis Oludemi': { table: 'Table 22 - Couple\'s Friends' },
  'Anosi Ojudin (has a baby)': { table: 'Table 22 - Couple\'s Friends' },
  'Opeyemi Ojudin': { table: 'Table 22 - Couple\'s Friends' },
  'Mrs Oluwaseun (Iya Precious)': { table: 'Table 23 - Bride\'s Mum\'s Friends' },
  'Mrs Toyin Kalejaiye (Iya Yemi)': { table: 'Table 23 - Bride\'s Mum\'s Friends' },
  'Mrs Ajoke': { table: 'Table 23 - Bride\'s Mum\'s Friends' },
  'Mrs Alimo ( Iya Darasimi )': { table: 'Table 23 - Bride\'s Mum\'s Friends' },
  'Mrs Bukky (Iya Fawaz )': { table: 'Table 23 - Bride\'s Mum\'s Friends' },
  'Mrs Kubura (Iya Enny)': { table: 'Table 23 - Bride\'s Mum\'s Friends' },
  'Mrs Basirat (Iya junior)': { table: 'Table 23 - Bride\'s Mum\'s Friends' },
  'Mrs Omoo (Iya Ibeji)': { table: 'Table 23 - Bride\'s Mum\'s Friends' },
  'Mr Gbolahan Oyaleye (Baba Aliyah)': { table: 'Table 23 - Bride\'s Mum\'s Friends' },
  'Mrs Aina Okorie': { table: 'Table 23 - Bride\'s Mum\'s Friends' },
  'SS Mrs Grace Ayodeji (Mama Esther)': { table: 'Table 24 - Apata Church' },
  'Esther Ayodeji': { table: 'Table 24 - Apata Church' },
  'Mrs Labake Ayodeji (Iya Deborah)': { table: 'Table 24 - Apata Church' },
  'Mrs Osai': { table: 'Table 24 - Apata Church' },
  'Mr Osai': { table: 'Table 24 - Apata Church' },
  'Mr Adenuga': { table: 'Table 24 - Apata Church' },
  'Mrs Adenuga': { table: 'Table 24 - Apata Church' },
  'Mrs Shobwale': { table: 'Table 24 - Apata Church' },
  'Mrs Shola Adelaja': { table: 'Table 24 - Apata Church' },
  'Mr Adelaja': { table: 'Table 24 - Apata Church' },
  'Marvelous Sunny': { table: 'Table 25 - First Bank Staff' },
  'Oluwapelumi Dosurumi': { table: 'Table 25 - First Bank Staff' },
  'Mr. Edwin Paul': { table: 'Table 25 - First Bank Staff' },
  'Mrs. Abibat Adeyemi': { table: 'Table 25 - First Bank Staff' },
  'Mr. Dare Benjamin': { table: 'Table 25 - First Bank Staff' },
  'Mrs. Comfort Amune': { table: 'Table 25 - First Bank Staff' },
  'Mr. Micheal Sebioba': { table: 'Table 25 - First Bank Staff' },
  'Moyinoluwa Oyeniran': { table: 'Table 25 - First Bank Staff' },
  'Oluwatosin Esan': { table: 'Table 25 - First Bank Staff' },
  'Racheal Adefunke': { table: 'Table 25 - First Bank Staff' },
  'Joseph Joshua': { table: 'Table 26 - Couple\'s Friends' },
  'Fuad Azeez': { table: 'Table 26 - Couple\'s Friends' },
  'Joshua James': { table: 'Table 26 - Couple\'s Friends' },
  'Oluwadarasimi Bolaji': { table: 'Table 26 - Couple\'s Friends' },
  'Oluwasegun Daramola': { table: 'Table 26 - Couple\'s Friends' },
  'Mr Musa Kaba': { table: 'Table 26 - Couple\'s Friends' },
  'Engr Ridwan Salam': { table: 'Table 26 - Couple\'s Friends' },
  'Engr Adekunle sodiq': { table: 'Table 26 - Couple\'s Friends' },
  'Dolapo Ayintete': { table: 'Table 26 - Couple\'s Friends' },
  'Aigbe Oluwadamilare': { table: 'Table 26 - Couple\'s Friends' },
  'Keji Anjorin': { table: 'Table 27 - Siblings\' Friends' },
  'Taiwo Fadeyi': { table: 'Table 27 - Siblings\' Friends' },
  'Benedicta Okerejifor': { table: 'Table 27 - Siblings\' Friends' },
  'Demilade Jowosimi': { table: 'Table 27 - Siblings\' Friends' },
  'Maria Sarwuarn': { table: 'Table 27 - Siblings\' Friends' },
  'Daniel': { table: 'Table 27 - Siblings\' Friends' },
  'Jacinta Okeke': { table: 'Table 27 - Siblings\' Friends' },
  'Mary Duru': { table: 'Table 27 - Siblings\' Friends' },
  'Favour Akanmu': { table: 'Table 27 - Siblings\' Friends' },
  'Stanley Okeke': { table: 'Table 27 - Siblings\' Friends' },
  'Mrs Folake (Final touch)': { table: 'Table 28 - Bride\'s Mum\'s Guests' },
  'Mrs Popoola': { table: 'Table 28 - Bride\'s Mum\'s Guests' },
  'Waliyat Popoola': { table: 'Table 28 - Bride\'s Mum\'s Guests' },
  'KB': { table: 'Table 28 - Bride\'s Mum\'s Guests' },
  'Engineer Bayo': { table: 'Table 28 - Bride\'s Mum\'s Guests' },
  'Mrs Olatokun (Iya Ife)': { table: 'Table 28 - Bride\'s Mum\'s Guests' },
  'Mr Olatokun (Baba Ife)': { table: 'Table 28 - Bride\'s Mum\'s Guests' },
  'Figo': { table: 'Table 28 - Bride\'s Mum\'s Guests' },
  'Engineer Biodun': { table: 'Table 28 - Bride\'s Mum\'s Guests' },
  'Mr Tewo': { table: 'Table 28 - Bride\'s Mum\'s Guests' },
  'Christian Nwayobuije': { table: 'Table 29 - Groom\'s Parents\' Guests' },
  'Madam Modinat': { table: 'Table 29 - Groom\'s Parents\' Guests' },
  'Mr. Benjamin': { table: 'Table 29 - Groom\'s Parents\' Guests' },
  'Mummy Ezekiel': { table: 'Table 29 - Groom\'s Parents\' Guests' },
  'Mrs Christiana': { table: 'Table 29 - Groom\'s Parents\' Guests' },
  'Mr Ademola': { table: 'Table 29 - Groom\'s Parents\' Guests' },
  'Abraham Dike': { table: 'Table 29 - Groom\'s Parents\' Guests' },
  'Treasure Dike': { table: 'Table 29 - Groom\'s Parents\' Guests' },
  'Mr Padonu': { table: 'Table 29 - Groom\'s Parents\' Guests' },
  'Mrs Padonu': { table: 'Table 29 - Groom\'s Parents\' Guests' },
  'Miss Kome': { table: 'Table 30' },
  'Mrs Kome (Mummy Ezekiel)': { table: 'Table 30' },
  'Wale Alabi': { table: 'Table 31 - Siblings\' Friends' },
  'Dafe Obukhowo': { table: 'Table 31 - Siblings\' Friends' },
  'Kareem Ademola': { table: 'Table 31 - Siblings\' Friends' },
  'Ife Monsuru': { table: 'Table 31 - Siblings\' Friends' },
  'Folarin Abiodun': { table: 'Table 31 - Siblings\' Friends' },
  'Tolani Saliba': { table: 'Table 31 - Siblings\' Friends' },
  'Ibrahim Ishola': { table: 'Table 31 - Siblings\' Friends' },
  'Kaosara': { table: 'Table 31 - Siblings\' Friends' },
  'Omo': { table: 'Table 31 - Siblings\' Friends' },
  'Barr. Ehigiator': { table: 'Table 32 - True Christian Life Church' },
  'Mrs. Josephine Ehigiator': { table: 'Table 32 - True Christian Life Church' },
  'Pastor Charles Okonkwo': { table: 'Table 32 - True Christian Life Church' },
  'Mrs. Onyinyechi Okonkwo': { table: 'Table 32 - True Christian Life Church' },
  'Pastor John Idebogle': { table: 'Table 32 - True Christian Life Church' },
  'Mrs. Joy Idebogle': { table: 'Table 32 - True Christian Life Church' },
  'Mrs. Joy Ifiobiya': { table: 'Table 32 - True Christian Life Church' },
  'Mrs. Stella Chigozie': { table: 'Table 32 - True Christian Life Church' },
  'Mrs. Felicia Samson': { table: 'Table 32 - True Christian Life Church' },
  'Mr. Emma Samson': { table: 'Table 32 - True Christian Life Church' },
  'Alfa Engineer': { table: 'Table 32 - Bride\'s Mum\'s Guests' },
  'Mr Tunji (Tungba)': { table: 'Table 32 - Bride\'s Mum\'s Guests' },
  'Iya Ife Oworo': { table: 'Table 32 - Bride\'s Mum\'s Guests' },
  'Temi Oworo': { table: 'Table 32 - Bride\'s Mum\'s Guests' },
  'Baba Foga': { table: 'Table 32 - Bride\'s Mum\'s Guests' },
  'Mr Muyiwa Osiloye': { table: 'Table 32 - Bride\'s Mum\'s Guests' },
  'Mrs Elizabeth Osiloye (has ONE child)': { table: 'Table 32 - Bride\'s Mum\'s Guests' },
  'Mrs Kareem': { table: 'Table 32 - Bride\'s Mum\'s Guests' },
  'Mrs Mojeed': { table: 'Table 32 - Bride\'s Mum\'s Guests' },
  'Oyem': { table: 'Table 32 - Bride\'s Mum\'s Guests' },
  'Mrs. Esther Bassey': { table: 'Table 33 - True Christian Life Church' },
  'Mr. Gbenga Origboye': { table: 'Table 33 - True Christian Life Church' },
  'Mrs. Chinwe Origboye': { table: 'Table 33 - True Christian Life Church' },
  'Mr. Nicholas Oke': { table: 'Table 33 - True Christian Life Church' },
  'Bro. Henry': { table: 'Table 33 - True Christian Life Church' },
  'Bro. Sunday Ani': { table: 'Table 33 - True Christian Life Church' },
  'Bro. Nosike': { table: 'Table 33 - True Christian Life Church' },
  'Mrs. Noye Nosike': { table: 'Table 33 - True Christian Life Church' },
  'Sis. Bridget Okate': { table: 'Table 33 - True Christian Life Church' },
  'Iya Emma': { table: 'Table 35 - Bride\'s Mum\'s Guests' },
  'Iya Alimoh': { table: 'Table 35 - Bride\'s Mum\'s Guests' },
  'Mummy David Orobo': { table: 'Table 35 - Bride\'s Mum\'s Guests' },
  'Mrs Okeke': { table: 'Table 35 - Bride\'s Mum\'s Guests' },
  'Baba Lawal': { table: 'Table 35 - Bride\'s Mum\'s Guests' },
  'Mrs Oyadara': { table: 'Table 35 - Bride\'s Mum\'s Guests' },
  'Mrs Adeniyi': { table: 'Table 35 - Bride\'s Mum\'s Guests' },
  'Mrs Okunubi': { table: 'Table 35 - Bride\'s Mum\'s Guests' },
  'Mrs Jumoke': { table: 'Table 35 - Bride\'s Mum\'s Guests' },
  'Ajulo Taiwo (Iya Drum)': { table: 'Table 35 - Bride\'s Mum\'s Guests' },
  'Tanimowo/Iya Dona Child 1': { table: 'Table 36 - Children' },
  'Tanimowo/Iya Dona Child 2': { table: 'Table 36 - Children' },
  'Bola Odetoki Child': { table: 'Table 36 - Children' },
  'Mrs Adejumo/Iya Dominion Child 1': { table: 'Table 36 - Children' },
  'Mrs Adejumo/Iya Dominion Child 2': { table: 'Table 36 - Children' },
  'Mrs Olaitan Idanwekhai Child 1': { table: 'Table 36 - Children' },
  'Mrs Olaitan Idanwekhai Child 2': { table: 'Table 36 - Children' },
  'Mrs Yemisi Omotunde Child': { table: 'Table 36 - Children' },
  'Mrs Elizabeth Osiloye Child': { table: 'Table 36 - Children' },
  'Mr & Mrs Mba Child 1': { table: 'Table 37 - Children' },
  'Mr & Mrs Mba Child 2': { table: 'Table 37 - Children' },
  'Mr & Mrs Mba Child 3': { table: 'Table 37 - Children' },
  'Mr & Mrs Mba Child 4': { table: 'Table 37 - Children' },
  'Mr & Mrs Mba Maid': { table: 'Table 37 - Children' },
  'Mr & Mrs Ighilo Children': { table: 'Table 37 - Children' },
  'Mr & Mrs Ighilo Maid': { table: 'Table 37 - Children' },
  'Favour Adetunmibi': { table: 'Table 38 - Odetoki Children' },
  'Daniel Adetunmibi': { table: 'Table 38 - Odetoki Children' },
  'Enoch Adetunmibi': { table: 'Table 38 - Odetoki Children' },
  'Kindness': { table: 'Table 38 - Odetoki Children' },
  'Happiness': { table: 'Table 38 - Odetoki Children' },
  'Goodness': { table: 'Table 38 - Odetoki Children' },
  'Greatness': { table: 'Table 38 - Odetoki Children' }
};

export default seatingChart;